### PR TITLE
ssh tunneling for access to servers behind the firewall

### PR DESCRIPTION
**Pull request by sfisher**
I've tested that this allows access to db, solr, merritt through my vagrant instance.

I can give you what I'm using to configure the tunnel in the config file.

### CODE REVIEW

**Comment by sfisher** [comment]
How to test that you can access the servers:

```
curl http://uc3-dryadsolr-dev.cdlib.org:8983/solr/
# You will get some HTML back instead of just a timeout with blocked access
```

```
curl --head http://uc3-mrtsword-dev.cdlib.org:39001/mrtsword/collection/dash_ucla
# you get headers back with unauthorized because you didn't supply user/password but
# you do not simply get a timeout from being blocked
```

```
$ mysql -u dryaddba -p -h uc3db-dash2-dev.cdlib.org dryad
# Enter password for DB access as shown in database.yml
# You should be let in and see a mysql prompt
# type 'show tables;' to see the tables in the database
# exit will take you out of mysql
```

**Comment by sfisher** [comment]
It looks like a dataset went through.  Was this in a different database?  I don't see the identifier doi:10.5072/FK2JS9RG1J in the dryad-dev database, but it got added to SOLR after Merritt seems to have successfully ingested it.

**Comment by daisieh** [comment]
I think I need to set the RAILS_ENV to development instead of local.

**Comment by sfisher** [comment]
Yeah,, that makes sense because all the parts need to match to go fully cycle so dev server database, dev-solr and dev-merritt.

We might be able to make it update a local solr server on a different machine and call back a different UI server to update a different database if we do some extras in what we submit to merritt as well as completely change how Merritt exposes different OAI-PMH feeds for every different development environment but it would be a lot of work to do so.

We can put a someday task in for it if we want, but I'm not sure how feasible it is to do it.

Separate Merritt instances would be a better solution, but you know about that story.  :-)

**Comment by daisieh** [comment]
I've restarted the rails server with RAILS_ENV=development and submitted another package. Let's see if that one goes through.

**Comment by daisieh** [comment]
Woohoo, the package submission went through!

**Comment by daisieh** [comment]
All of the specified tests work now. This looks good. Merging.

**Pull request merged**
